//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.2
//     from Assets/InputSystem/AnimationControl.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Lonize
{
    /// <summary>
    /// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/InputSystem/AnimationControl.inputactions".
    /// </summary>
    /// <remarks>
    /// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
    /// </remarks>
    /// <example>
    /// <code>
    /// using namespace UnityEngine;
    /// using UnityEngine.InputSystem;
    ///
    /// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
    /// public class Example : MonoBehaviour, MyActions.IPlayerActions
    /// {
    ///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
    ///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
    ///
    ///     void Awake()
    ///     {
    ///         m_Actions = new MyActions_Actions();              // Create asset object.
    ///         m_Player = m_Actions.Player;                      // Extract action map object.
    ///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
    ///     }
    ///
    ///     void OnDestroy()
    ///     {
    ///         m_Actions.Dispose();                              // Destroy asset object.
    ///     }
    ///
    ///     void OnEnable()
    ///     {
    ///         m_Player.Enable();                                // Enable all actions within map.
    ///     }
    ///
    ///     void OnDisable()
    ///     {
    ///         m_Player.Disable();                               // Disable all actions within map.
    ///     }
    ///
    ///     #region Interface implementation of MyActions.IPlayerActions
    ///
    ///     // Invoked when "Move" action is either started, performed or canceled.
    ///     public void OnMove(InputAction.CallbackContext context)
    ///     {
    ///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
    ///     }
    ///
    ///     // Invoked when "Attack" action is either started, performed or canceled.
    ///     public void OnAttack(InputAction.CallbackContext context)
    ///     {
    ///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
    ///     }
    ///
    ///     #endregion
    /// }
    /// </code>
    /// </example>
    public partial class @AnimationControls: IInputActionCollection2, IDisposable
    {
        /// <summary>
        /// Provides access to the underlying asset instance.
        /// </summary>
        public InputActionAsset asset { get; }

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public @AnimationControls()
        {
            asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""AnimationControl"",
    ""maps"": [
        {
            ""name"": ""Animation"",
            ""id"": ""248a6a9d-4e0c-402e-9307-ba45b8a7b139"",
            ""actions"": [
                {
                    ""name"": ""ET1"",
                    ""type"": ""Button"",
                    ""id"": ""3292dc22-a864-41b5-ab8e-b0faefb249da"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ET2"",
                    ""type"": ""Button"",
                    ""id"": ""333646b7-b55a-4ea0-9cfe-3bf1f58fc6e6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a889b1ed-cfc2-481a-a438-481b7cf65042"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ET1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f7a599d2-a2eb-4904-b09d-d6fbf66b1f09"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ET2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Instantiate"",
            ""id"": ""ac82c70f-3251-4894-93d9-4bed17829c62"",
            ""actions"": [
                {
                    ""name"": ""Cube"",
                    ""type"": ""Button"",
                    ""id"": ""85afe71b-af0d-49d0-8fc3-e58b05c8a279"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d7b1f4eb-5342-46f8-8b3d-758c54ed84d8"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cube"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Animation
            m_Animation = asset.FindActionMap("Animation", throwIfNotFound: true);
            m_Animation_ET1 = m_Animation.FindAction("ET1", throwIfNotFound: true);
            m_Animation_ET2 = m_Animation.FindAction("ET2", throwIfNotFound: true);
            // Instantiate
            m_Instantiate = asset.FindActionMap("Instantiate", throwIfNotFound: true);
            m_Instantiate_Cube = m_Instantiate.FindAction("Cube", throwIfNotFound: true);
        }

        ~@AnimationControls()
        {
            UnityEngine.Debug.Assert(!m_Animation.enabled, "This will cause a leak and performance issues, AnimationControls.Animation.Disable() has not been called.");
            UnityEngine.Debug.Assert(!m_Instantiate.enabled, "This will cause a leak and performance issues, AnimationControls.Instantiate.Disable() has not been called.");
        }

        /// <summary>
        /// Destroys this asset and all associated <see cref="InputAction"/> instances.
        /// </summary>
        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
        public void Enable()
        {
            asset.Enable();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
        public void Disable()
        {
            asset.Disable();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
        public IEnumerable<InputBinding> bindings => asset.bindings;

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Animation
        private readonly InputActionMap m_Animation;
        private List<IAnimationActions> m_AnimationActionsCallbackInterfaces = new List<IAnimationActions>();
        private readonly InputAction m_Animation_ET1;
        private readonly InputAction m_Animation_ET2;
        /// <summary>
        /// Provides access to input actions defined in input action map "Animation".
        /// </summary>
        public struct AnimationActions
        {
            private @AnimationControls m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public AnimationActions(@AnimationControls wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "Animation/ET1".
            /// </summary>
            public InputAction @ET1 => m_Wrapper.m_Animation_ET1;
            /// <summary>
            /// Provides access to the underlying input action "Animation/ET2".
            /// </summary>
            public InputAction @ET2 => m_Wrapper.m_Animation_ET2;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_Animation; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="AnimationActions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(AnimationActions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="AnimationActions" />
            public void AddCallbacks(IAnimationActions instance)
            {
                if (instance == null || m_Wrapper.m_AnimationActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_AnimationActionsCallbackInterfaces.Add(instance);
                @ET1.started += instance.OnET1;
                @ET1.performed += instance.OnET1;
                @ET1.canceled += instance.OnET1;
                @ET2.started += instance.OnET2;
                @ET2.performed += instance.OnET2;
                @ET2.canceled += instance.OnET2;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="AnimationActions" />
            private void UnregisterCallbacks(IAnimationActions instance)
            {
                @ET1.started -= instance.OnET1;
                @ET1.performed -= instance.OnET1;
                @ET1.canceled -= instance.OnET1;
                @ET2.started -= instance.OnET2;
                @ET2.performed -= instance.OnET2;
                @ET2.canceled -= instance.OnET2;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="AnimationActions.UnregisterCallbacks(IAnimationActions)" />.
            /// </summary>
            /// <seealso cref="AnimationActions.UnregisterCallbacks(IAnimationActions)" />
            public void RemoveCallbacks(IAnimationActions instance)
            {
                if (m_Wrapper.m_AnimationActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="AnimationActions.AddCallbacks(IAnimationActions)" />
            /// <seealso cref="AnimationActions.RemoveCallbacks(IAnimationActions)" />
            /// <seealso cref="AnimationActions.UnregisterCallbacks(IAnimationActions)" />
            public void SetCallbacks(IAnimationActions instance)
            {
                foreach (var item in m_Wrapper.m_AnimationActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_AnimationActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="AnimationActions" /> instance referencing this action map.
        /// </summary>
        public AnimationActions @Animation => new AnimationActions(this);

        // Instantiate
        private readonly InputActionMap m_Instantiate;
        private List<IInstantiateActions> m_InstantiateActionsCallbackInterfaces = new List<IInstantiateActions>();
        private readonly InputAction m_Instantiate_Cube;
        /// <summary>
        /// Provides access to input actions defined in input action map "Instantiate".
        /// </summary>
        public struct InstantiateActions
        {
            private @AnimationControls m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public InstantiateActions(@AnimationControls wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "Instantiate/Cube".
            /// </summary>
            public InputAction @Cube => m_Wrapper.m_Instantiate_Cube;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_Instantiate; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="InstantiateActions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(InstantiateActions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="InstantiateActions" />
            public void AddCallbacks(IInstantiateActions instance)
            {
                if (instance == null || m_Wrapper.m_InstantiateActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_InstantiateActionsCallbackInterfaces.Add(instance);
                @Cube.started += instance.OnCube;
                @Cube.performed += instance.OnCube;
                @Cube.canceled += instance.OnCube;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="InstantiateActions" />
            private void UnregisterCallbacks(IInstantiateActions instance)
            {
                @Cube.started -= instance.OnCube;
                @Cube.performed -= instance.OnCube;
                @Cube.canceled -= instance.OnCube;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="InstantiateActions.UnregisterCallbacks(IInstantiateActions)" />.
            /// </summary>
            /// <seealso cref="InstantiateActions.UnregisterCallbacks(IInstantiateActions)" />
            public void RemoveCallbacks(IInstantiateActions instance)
            {
                if (m_Wrapper.m_InstantiateActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="InstantiateActions.AddCallbacks(IInstantiateActions)" />
            /// <seealso cref="InstantiateActions.RemoveCallbacks(IInstantiateActions)" />
            /// <seealso cref="InstantiateActions.UnregisterCallbacks(IInstantiateActions)" />
            public void SetCallbacks(IInstantiateActions instance)
            {
                foreach (var item in m_Wrapper.m_InstantiateActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_InstantiateActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="InstantiateActions" /> instance referencing this action map.
        /// </summary>
        public InstantiateActions @Instantiate => new InstantiateActions(this);
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Animation" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="AnimationActions.AddCallbacks(IAnimationActions)" />
        /// <seealso cref="AnimationActions.RemoveCallbacks(IAnimationActions)" />
        public interface IAnimationActions
        {
            /// <summary>
            /// Method invoked when associated input action "ET1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnET1(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "ET2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnET2(InputAction.CallbackContext context);
        }
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Instantiate" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="InstantiateActions.AddCallbacks(IInstantiateActions)" />
        /// <seealso cref="InstantiateActions.RemoveCallbacks(IInstantiateActions)" />
        public interface IInstantiateActions
        {
            /// <summary>
            /// Method invoked when associated input action "Cube" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnCube(InputAction.CallbackContext context);
        }
    }
}
