//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.2
//     from Assets/InputSystem/Dev Control.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Lonize
{
    /// <summary>
    /// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/InputSystem/Dev Control.inputactions".
    /// </summary>
    /// <remarks>
    /// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
    /// </remarks>
    /// <example>
    /// <code>
    /// using namespace UnityEngine;
    /// using UnityEngine.InputSystem;
    ///
    /// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
    /// public class Example : MonoBehaviour, MyActions.IPlayerActions
    /// {
    ///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
    ///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
    ///
    ///     void Awake()
    ///     {
    ///         m_Actions = new MyActions_Actions();              // Create asset object.
    ///         m_Player = m_Actions.Player;                      // Extract action map object.
    ///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
    ///     }
    ///
    ///     void OnDestroy()
    ///     {
    ///         m_Actions.Dispose();                              // Destroy asset object.
    ///     }
    ///
    ///     void OnEnable()
    ///     {
    ///         m_Player.Enable();                                // Enable all actions within map.
    ///     }
    ///
    ///     void OnDisable()
    ///     {
    ///         m_Player.Disable();                               // Disable all actions within map.
    ///     }
    ///
    ///     #region Interface implementation of MyActions.IPlayerActions
    ///
    ///     // Invoked when "Move" action is either started, performed or canceled.
    ///     public void OnMove(InputAction.CallbackContext context)
    ///     {
    ///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
    ///     }
    ///
    ///     // Invoked when "Attack" action is either started, performed or canceled.
    ///     public void OnAttack(InputAction.CallbackContext context)
    ///     {
    ///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
    ///     }
    ///
    ///     #endregion
    /// }
    /// </code>
    /// </example>
    public partial class @DevControls: IInputActionCollection2, IDisposable
    {
        /// <summary>
        /// Provides access to the underlying asset instance.
        /// </summary>
        public InputActionAsset asset { get; }

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public @DevControls()
        {
            asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""Dev Control"",
    ""maps"": [
        {
            ""name"": ""Map"",
            ""id"": ""51838c01-955d-48a2-a5f4-2b0b0f219a4b"",
            ""actions"": [
                {
                    ""name"": ""RegenerateMiniMap"",
                    ""type"": ""Button"",
                    ""id"": ""3c111978-8d05-455e-9524-e3821015fbe0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RegenerateWorldMap"",
                    ""type"": ""Button"",
                    ""id"": ""3b96a9c0-33ce-4e5f-a62b-2510f7248270"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ClearWorldMap"",
                    ""type"": ""Button"",
                    ""id"": ""b87b4b0a-92ea-4f6e-9c09-9506b2942037"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""75ed49d6-d846-454f-a70d-651c6a2354b8"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RegenerateMiniMap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0041da6d-aebe-4223-8de5-1df91682f3b5"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RegenerateWorldMap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""958bc888-cfea-43a5-b8d7-3523f38629bf"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClearWorldMap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Building"",
            ""id"": ""099b0c41-1d25-486e-a719-ed58e0b7f49d"",
            ""actions"": [
                {
                    ""name"": ""PrintInfo"",
                    ""type"": ""Button"",
                    ""id"": ""43f19ff5-af87-45fc-923c-465744e75db4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""899b20e2-e42a-4a7b-9635-e7c8331b9d10"",
                    ""path"": ""<Keyboard>/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrintInfo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Console"",
            ""id"": ""78e4f67f-4ab8-4ea0-9f67-a180ff173c21"",
            ""actions"": [
                {
                    ""name"": ""Open"",
                    ""type"": ""Button"",
                    ""id"": ""7d3f364c-654d-465c-b855-ab9672d57194"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""aca9627b-1641-4c82-9411-2dfce84bc300"",
                    ""path"": ""<Keyboard>/backquote"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Open"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Map
            m_Map = asset.FindActionMap("Map", throwIfNotFound: true);
            m_Map_RegenerateMiniMap = m_Map.FindAction("RegenerateMiniMap", throwIfNotFound: true);
            m_Map_RegenerateWorldMap = m_Map.FindAction("RegenerateWorldMap", throwIfNotFound: true);
            m_Map_ClearWorldMap = m_Map.FindAction("ClearWorldMap", throwIfNotFound: true);
            // Building
            m_Building = asset.FindActionMap("Building", throwIfNotFound: true);
            m_Building_PrintInfo = m_Building.FindAction("PrintInfo", throwIfNotFound: true);
            // Console
            m_Console = asset.FindActionMap("Console", throwIfNotFound: true);
            m_Console_Open = m_Console.FindAction("Open", throwIfNotFound: true);
        }

        ~@DevControls()
        {
            UnityEngine.Debug.Assert(!m_Map.enabled, "This will cause a leak and performance issues, DevControls.Map.Disable() has not been called.");
            UnityEngine.Debug.Assert(!m_Building.enabled, "This will cause a leak and performance issues, DevControls.Building.Disable() has not been called.");
            UnityEngine.Debug.Assert(!m_Console.enabled, "This will cause a leak and performance issues, DevControls.Console.Disable() has not been called.");
        }

        /// <summary>
        /// Destroys this asset and all associated <see cref="InputAction"/> instances.
        /// </summary>
        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
        public void Enable()
        {
            asset.Enable();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
        public void Disable()
        {
            asset.Disable();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
        public IEnumerable<InputBinding> bindings => asset.bindings;

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Map
        private readonly InputActionMap m_Map;
        private List<IMapActions> m_MapActionsCallbackInterfaces = new List<IMapActions>();
        private readonly InputAction m_Map_RegenerateMiniMap;
        private readonly InputAction m_Map_RegenerateWorldMap;
        private readonly InputAction m_Map_ClearWorldMap;
        /// <summary>
        /// Provides access to input actions defined in input action map "Map".
        /// </summary>
        public struct MapActions
        {
            private @DevControls m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public MapActions(@DevControls wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "Map/RegenerateMiniMap".
            /// </summary>
            public InputAction @RegenerateMiniMap => m_Wrapper.m_Map_RegenerateMiniMap;
            /// <summary>
            /// Provides access to the underlying input action "Map/RegenerateWorldMap".
            /// </summary>
            public InputAction @RegenerateWorldMap => m_Wrapper.m_Map_RegenerateWorldMap;
            /// <summary>
            /// Provides access to the underlying input action "Map/ClearWorldMap".
            /// </summary>
            public InputAction @ClearWorldMap => m_Wrapper.m_Map_ClearWorldMap;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_Map; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="MapActions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(MapActions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="MapActions" />
            public void AddCallbacks(IMapActions instance)
            {
                if (instance == null || m_Wrapper.m_MapActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_MapActionsCallbackInterfaces.Add(instance);
                @RegenerateMiniMap.started += instance.OnRegenerateMiniMap;
                @RegenerateMiniMap.performed += instance.OnRegenerateMiniMap;
                @RegenerateMiniMap.canceled += instance.OnRegenerateMiniMap;
                @RegenerateWorldMap.started += instance.OnRegenerateWorldMap;
                @RegenerateWorldMap.performed += instance.OnRegenerateWorldMap;
                @RegenerateWorldMap.canceled += instance.OnRegenerateWorldMap;
                @ClearWorldMap.started += instance.OnClearWorldMap;
                @ClearWorldMap.performed += instance.OnClearWorldMap;
                @ClearWorldMap.canceled += instance.OnClearWorldMap;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="MapActions" />
            private void UnregisterCallbacks(IMapActions instance)
            {
                @RegenerateMiniMap.started -= instance.OnRegenerateMiniMap;
                @RegenerateMiniMap.performed -= instance.OnRegenerateMiniMap;
                @RegenerateMiniMap.canceled -= instance.OnRegenerateMiniMap;
                @RegenerateWorldMap.started -= instance.OnRegenerateWorldMap;
                @RegenerateWorldMap.performed -= instance.OnRegenerateWorldMap;
                @RegenerateWorldMap.canceled -= instance.OnRegenerateWorldMap;
                @ClearWorldMap.started -= instance.OnClearWorldMap;
                @ClearWorldMap.performed -= instance.OnClearWorldMap;
                @ClearWorldMap.canceled -= instance.OnClearWorldMap;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="MapActions.UnregisterCallbacks(IMapActions)" />.
            /// </summary>
            /// <seealso cref="MapActions.UnregisterCallbacks(IMapActions)" />
            public void RemoveCallbacks(IMapActions instance)
            {
                if (m_Wrapper.m_MapActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="MapActions.AddCallbacks(IMapActions)" />
            /// <seealso cref="MapActions.RemoveCallbacks(IMapActions)" />
            /// <seealso cref="MapActions.UnregisterCallbacks(IMapActions)" />
            public void SetCallbacks(IMapActions instance)
            {
                foreach (var item in m_Wrapper.m_MapActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_MapActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="MapActions" /> instance referencing this action map.
        /// </summary>
        public MapActions @Map => new MapActions(this);

        // Building
        private readonly InputActionMap m_Building;
        private List<IBuildingActions> m_BuildingActionsCallbackInterfaces = new List<IBuildingActions>();
        private readonly InputAction m_Building_PrintInfo;
        /// <summary>
        /// Provides access to input actions defined in input action map "Building".
        /// </summary>
        public struct BuildingActions
        {
            private @DevControls m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public BuildingActions(@DevControls wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "Building/PrintInfo".
            /// </summary>
            public InputAction @PrintInfo => m_Wrapper.m_Building_PrintInfo;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_Building; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="BuildingActions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(BuildingActions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="BuildingActions" />
            public void AddCallbacks(IBuildingActions instance)
            {
                if (instance == null || m_Wrapper.m_BuildingActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_BuildingActionsCallbackInterfaces.Add(instance);
                @PrintInfo.started += instance.OnPrintInfo;
                @PrintInfo.performed += instance.OnPrintInfo;
                @PrintInfo.canceled += instance.OnPrintInfo;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="BuildingActions" />
            private void UnregisterCallbacks(IBuildingActions instance)
            {
                @PrintInfo.started -= instance.OnPrintInfo;
                @PrintInfo.performed -= instance.OnPrintInfo;
                @PrintInfo.canceled -= instance.OnPrintInfo;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="BuildingActions.UnregisterCallbacks(IBuildingActions)" />.
            /// </summary>
            /// <seealso cref="BuildingActions.UnregisterCallbacks(IBuildingActions)" />
            public void RemoveCallbacks(IBuildingActions instance)
            {
                if (m_Wrapper.m_BuildingActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="BuildingActions.AddCallbacks(IBuildingActions)" />
            /// <seealso cref="BuildingActions.RemoveCallbacks(IBuildingActions)" />
            /// <seealso cref="BuildingActions.UnregisterCallbacks(IBuildingActions)" />
            public void SetCallbacks(IBuildingActions instance)
            {
                foreach (var item in m_Wrapper.m_BuildingActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_BuildingActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="BuildingActions" /> instance referencing this action map.
        /// </summary>
        public BuildingActions @Building => new BuildingActions(this);

        // Console
        private readonly InputActionMap m_Console;
        private List<IConsoleActions> m_ConsoleActionsCallbackInterfaces = new List<IConsoleActions>();
        private readonly InputAction m_Console_Open;
        /// <summary>
        /// Provides access to input actions defined in input action map "Console".
        /// </summary>
        public struct ConsoleActions
        {
            private @DevControls m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public ConsoleActions(@DevControls wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "Console/Open".
            /// </summary>
            public InputAction @Open => m_Wrapper.m_Console_Open;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_Console; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="ConsoleActions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(ConsoleActions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="ConsoleActions" />
            public void AddCallbacks(IConsoleActions instance)
            {
                if (instance == null || m_Wrapper.m_ConsoleActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_ConsoleActionsCallbackInterfaces.Add(instance);
                @Open.started += instance.OnOpen;
                @Open.performed += instance.OnOpen;
                @Open.canceled += instance.OnOpen;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="ConsoleActions" />
            private void UnregisterCallbacks(IConsoleActions instance)
            {
                @Open.started -= instance.OnOpen;
                @Open.performed -= instance.OnOpen;
                @Open.canceled -= instance.OnOpen;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="ConsoleActions.UnregisterCallbacks(IConsoleActions)" />.
            /// </summary>
            /// <seealso cref="ConsoleActions.UnregisterCallbacks(IConsoleActions)" />
            public void RemoveCallbacks(IConsoleActions instance)
            {
                if (m_Wrapper.m_ConsoleActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="ConsoleActions.AddCallbacks(IConsoleActions)" />
            /// <seealso cref="ConsoleActions.RemoveCallbacks(IConsoleActions)" />
            /// <seealso cref="ConsoleActions.UnregisterCallbacks(IConsoleActions)" />
            public void SetCallbacks(IConsoleActions instance)
            {
                foreach (var item in m_Wrapper.m_ConsoleActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_ConsoleActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="ConsoleActions" /> instance referencing this action map.
        /// </summary>
        public ConsoleActions @Console => new ConsoleActions(this);
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Map" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="MapActions.AddCallbacks(IMapActions)" />
        /// <seealso cref="MapActions.RemoveCallbacks(IMapActions)" />
        public interface IMapActions
        {
            /// <summary>
            /// Method invoked when associated input action "RegenerateMiniMap" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnRegenerateMiniMap(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "RegenerateWorldMap" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnRegenerateWorldMap(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "ClearWorldMap" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnClearWorldMap(InputAction.CallbackContext context);
        }
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Building" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="BuildingActions.AddCallbacks(IBuildingActions)" />
        /// <seealso cref="BuildingActions.RemoveCallbacks(IBuildingActions)" />
        public interface IBuildingActions
        {
            /// <summary>
            /// Method invoked when associated input action "PrintInfo" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnPrintInfo(InputAction.CallbackContext context);
        }
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Console" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="ConsoleActions.AddCallbacks(IConsoleActions)" />
        /// <seealso cref="ConsoleActions.RemoveCallbacks(IConsoleActions)" />
        public interface IConsoleActions
        {
            /// <summary>
            /// Method invoked when associated input action "Open" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnOpen(InputAction.CallbackContext context);
        }
    }
}
